apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
  name: my-broker
spec:
  acceptors:
    - expose: true
      name: all
      port: 61617
      protocols: all
      sslEnabled: true
      sslProvider: JDK
      sslSecret: amqbroker-tls-secret
      verifyHost: false
  adminPassword: admin
  adminUser: admin
  connectors:
    - expose: true
      host: localhost
      name: connector0
      port: 22222
      sslProvider: JDK
  console:
    expose: true
  deploymentPlan:
    image: 'registry.redhat.io/amq7/amq-broker:7.7'
    journalType: nio
    messageMigration: true
    persistenceEnabled: true
    requireLogin: true
    size: 2
